#!/bin/bash
git checkout richel
git pull

for branch in bruno daan jasper jesper jonas judith kyrill mees oliver quinn richel rohan seny 
do
  git checkout $branch
  git pull
  git checkout richel
  git merge $branch
  git push
done

git checkout richel
